### ISSUE TITLE
failed loading configuration file protractor.conf.js ( Protractor Version 5.2.0 )

### ISSUE THREAD

**Issue by 007muditha** [99xt/CodeSpecJS#18]
This exception occurs when I tried to run the test

[12:29:41] E/configParser - Error code: 105
[12:29:41] E/configParser - Error message: failed loading configuration file protractor.conf.js
[12:29:41] E/configParser - Error: Cannot find module 'protractor'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Muditha\git\CodeSpecJS\protractor.conf.js:4:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by surenr** [comment]
Have you done a npm install after cloning the project? error seems to suggest the protractor module can't be found.

**Comment by sandali1991** [comment]
I also got that issue. After i install npm, it worked 😄

**Comment by 007muditha** [comment]
@surenr 
Thank you for the update :) Will check on that

**Comment by Shabbir124** [comment]
Error message: failed loading configuration file conf.js
may i know the solution of this problem? :(

**Comment by sparsh13h** [comment]
@Shabbir124 : I was facing the same error . While saving conf.js we need to add "conf.js" so as to make the file as javascript file else it will take it as a text file only. So just save conf.js file as "conf.js" and similarly spec file also and it will work.

**Comment by mogwaipr** [comment]
I am trying to add cucumber-protractor-steps to a cucumber-protractor-selenium docker image.  For some reason it cannot load the module when I run the project.

**Comment by alessandrocode09** [comment]
I have the same issue, but i don't know the solution, somebody can help me ?

conf.js:

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['spec.js']
};

spec.js:
describe('Protractor Demo App', function(){
    it('test tile', function() {
        browser.get('http://demo.redmine.org/');
    });
});

When a run this line "protractor conf.js" i have this issue:

[13:52:11] E/configParser - Error code: 105
[13:52:11] E/configParser - Error message: failed loading configuration file conf.js
[13:52:11] E/configParser - C:\Users\User\Documents\Projects\projectProtactor\conf.js:1
(function (exports, require, module, __filename, __dirname) { ��e
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:686:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)


Somebody can help me please ?

**Comment by Durgam777** [comment]
I too facing the same issues when only try to create an instance of module/page in the 'beforeLaunch' hook in the config.ts file. If commented the 'beforeLaunch' code it is working as expected, below is my config.ts file looks -

config.ts
========
import { ProtractorBrowser, Config } from 'protractor';
import {reportingServiceAPIs} from './src/pages/reportingService/quickScreen/reportingServiceAPIs'
export let config: Config = {
  //importing test data JSON files from testData folder

  params: {
    testData: require('./../src/testData/demoTestData.json'),
    apiTestData: require('./../src/testData/reportServiceAPIRequestData.json'),
  },

  seleniumAddress: 'http://localhost:4444/wd/hub',
  capabilities: {
    'browserName': 'chrome'
    },
  // directConnect:false,//true=local , false=grid
  framework: 'jasmine',
  specs: [
    './src/testSpec/sample/testspec.2.js'
    // './src/testSpec/sample/testspec.3.js'
    // './src/testSpec/sample/testDataCreationSpec.js'
    // './src/testSpec/sample/properties_ReaderSpec.js'
    
    
  ],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 90000
  },
  
  onPrepare: () => {
    console.log(" Started onPrepare ")
   let globals = require('protractor');
   let browser = globals.browser;
   browser.manage().window().maximize();
   browser.manage().timeouts().implicitlyWait(5000);
 },
 beforeLaunch:() => {
  console.log("Started beforeLaunch")
  let api=new reportingServiceAPIs()
  let access_token=api.getCerberusAuthenticationTokenAPI('xxxxxxxxxxx','xxxxxxxxxxxxx');
  console.log("access token from beforeLaunch ====================\n" + access_token)
  }
}

Please refer the error -

> protractor ./convertedJSFiles/config.js

[17:30:19] E/configParser - Error code: 105
[17:30:19] E/configParser - Error message: failed loading configuration file ./convertedJSFiles/config.js
[17:30:19] E/configParser - TypeError: Cannot read property 'params' of undefined
    at Object.<anonymous> (E:\platform2.0\Repos\Final\protomation-suite\convertedJSFiles\src\pages\reportingService\quickScreen\reportingServiceAPIs.js:48:40)

**Comment by Durgam777** [comment]
I got to know the issue is, in the confg.js file, there is 'params' block where I pointed to some test JSON files, these are invoked from page-level but if I call from config.js file its kind of ambiguous due to this params block is not functioning correctly.
I passed the params object from config.js to Page-level class it's working, rather than calling from page-level

**Comment by Naveen2226** [comment]
I am unable to generate reports in protractor

//config.js
var HtmlReporter = require('protractor-html-screenshot-reporter');

exports.config = {
	framework : 'jasmine',
	seleniumAddress : 'http://localhost:4444/wd/hub',
	specs : ['EmpCreation.js'],
	
	 onPrepare: function() {
	      // Add a screenshot reporter and store screenshots to `/tmp/screnshots`:
	      jasmine.getEnv().addReporter(new HtmlReporter({
	         baseDirectory: '/tmp/screenshots'
	      }));
	   }
};


//Error
 E:\Core\MyFirstProtractor\src\Day2>protractor config3.js
[12:55:03] E/configParser - Error code: 105
[12:55:03] E/configParser - Error message: failed loading configuration file config3.js
[12:55:03] E/configParser - Error: Cannot find module 'protractor-html-screenshot-reporter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\Core\MyFirstProtractor\src\Day2\config3.js:1:82)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by priyanka111111** [comment]
Somebody, please help I still facing the issue

failed loading configuration file conf.js [18:45:35] E/configParser - ReferenceError: spec1 is not defined

**Comment by mzali1900** [comment]
I am having same issue 
Error Code : 105
Error message: failed loading configuration file config.js
Error: cannot find module 'C:\\automation-factory-develop\FolderProtractorAutomation\config.js

**Comment by hzainguyen** [comment]
I'm having same issue:
`[10:14:35] E/configParser - Error code: 105
[10:14:35] E/configParser - Error message: failed loading configuration file ./test-config/protractor.conf.js
[10:14:35] E/configParser - Error: EIO: i/o error, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:575:19)
    at Object.Module._extensions..js (module.js:663:20)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\HNL\pwa\node_modules\jasmine-spec-reporter\built\spec-reporter.js:6:25)
`


> Have you done a npm install after cloning the project? error seems to suggest the protractor module can't be found.

Still not working !

**Comment by ingriddbritok3** [comment]
I am having the same issue, but just after run the following command: 
`npm install --save-dev sg-protractor-tools `
After this command, I can not run any config file. Does anyone know how to fix or revert this?

**Comment by anshulchhajed** [comment]
Use the below snippet. This worked for me
I jst added missing comma after specs in the script.

var HtmlReporter = require('protractor-beautiful-reporter');

exports.config = {
		seleniumAddress: 'http://localhost:4444/wd/hub',
		specs: ['firsttest.js'],

onPrepare: function() {
	// Add a screenshot reporter and store screenshots to `/tmp/screenshots`:
	jasmine.getEnv().addReporter(new HtmlReporter({
		baseDirectory: 'tmp/screenshots'
	}).getJasmine2Reporter());
}
}

**Comment by Umer919** [comment]
PS C:\Users\Ahsan\Desktop\Projects> protractor .\conf\conf.js
[00:56:25] E/configParser - Error code: 105
[00:56:25] E/configParser - Error message: failed loading configuration file .\conf\conf.js
[00:56:25] E/configParser - Error: Cannot find module 'C:\Users\Ahsan\Desktop\Projects\conf\conf.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at ConfigParser.addFileConfig (C:\Users\Ahsan\AppData\Roaming\npm\node_modules\protractor\built\configParser.js:135:26)
    at Object.initFn [as init] (C:\Users\Ahsan\AppData\Roaming\npm\node_modules\protractor\built\launcher.js:93:22)
    at Object.<anonymous> (C:\Users\Ahsan\AppData\Roaming\npm\node_modules\protractor\built\cli.js:227:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
PS C:\Users\Ahsan\Desktop\Projects>

I am Having the Same Issue ,someone please suggest me the solution

**Comment by sensay9** [comment]
In my case, I had a freshly installed node which made the existing protractor project causing this type of errors. To fix this issue, I had to install npm with **npm install npm@latest -g** and then ** webdriver-manager update** command to update the driver.

**Comment by Shaveta872** [comment]
Solution for protractor screenshot issue
Installed globally

npm install -g  protractor-jasmine2-html-reporter

Run below command to link protractor and jasmine2-html-reporter to aovid report not generating issue. Please see Girish Sortur's answer in How to create Protractor reports with Jasmine2

npm link protractor-jasmine2-html-reporter

Also add this import with path to exact node module to avoid the error in windows 10

var Jasmine2HtmlReporter = require('C:/Users/sam/AppData/Roaming/npm/node_modules/protractor-



var Jasmine2HtmlReporter = require('C:/Users/sam/AppData/Roaming/npm/node_modules/protractor-jasmine2-html-reporter');

exports.config = {
  framework: 'jasmine',

 capabilities: {
browserName: 'chrome',
chromeOptions: {
args: [ "--start-maximized" ]
         }
    },

      onPrepare: function() {
          jasmine.getEnv().addReporter(
            new Jasmine2HtmlReporter({
           takeScreenshots: true,// By default this is enabled Default is true
           takeScreenshotsOnlyOnFailures: false, // Default is false (So screenshots are always generated)
           cleanDestination: true, // if false, will not delete the reports or screenshots before each test run.Default is true
           showPassed: true,//default is true This option, if false, will show only failures.
           fileName: 'MyRepoDemo', //We can give a prefered file name .
           savePath: 'myproreports',//Reports location it will automatically generated
           screenshotsFolder: 'screenshotsloc' //Screenshot location it will create a folder inside myproreports
            })
          );
       },
